#Excercise of Viterbi

In [0]:
import numpy as np

##Data

In [0]:
n_x = 4
n_y = 4
pyy = np.zeros((n_y,n_y))
pyx = np.zeros((n_y,n_x))

#P(y->y) 
#y: 0-Party 1-Tv 2-Pub 3-Study
pyy[0] = np.array([0.05, 0.7, 0.05, 0.2])
pyy[1] = np.array([0.1,  0.4, 0.3, 0.2 ])
pyy[2] = np.array([0.1,  0.6, 0.05, 0.25])
pyy[3] = np.array([0.25, 0.3, 0.4, 0.05])

#p(x|y) 
#y : 0-Party 1-Tv 2-Pub 3-Study; 
#x : 0-tired 1-hungover 2-scared 3-fine;
pyx[0] = np.array([0.3, 0.4, 0.2, 0.1])
pyx[1] = np.array([0.2, 0.1, 0.2, 0.5])
pyx[2] = np.array([0.4, 0.2, 0.1, 0.3])
pyx[3] = np.array([0.3, 0.05, 0.3, 0.35])


'''n_x = 4
n_y = 2
pyy = np.zeros((n_y,n_y))
pyx = np.zeros((n_y,n_x))
pyy[0] = np.array([0.5,0.5])
pyy[1] = np.array([0.4,0.6])
pyx[0] = np.array([0.2, 0.3, 0.3, 0.2])
pyx[1] = np.array([0.3, 0.2, 0.2, 0.3])
'''

pyy = np.log2(pyy)
pyx = np.log2(pyx)


##Implement

In [0]:
def mapCharacter(n):
	return {
		0: 'Party',1: 'Tv',2: 'Pub',3: 'Study'
				}.get(n,'null')

In [0]:
# request 
input = np.array([2,2,1,0,1,3,2,0,0]) # tired-tired-scared


In [371]:
p0 = np.log2(np.ones((n_y,)) / n_y)
result = np.zeros((n_y,))
p = np.zeros((len(input) ,n_y))
p[0] = p0 + pyx[:, input[0]]
track = np.zeros((len(input),n_y), dtype = np.int) - 1

for i in range(len(input) - 1):
  x = input[i + 1]
  ip = i + 1 
  for y in range(n_y):
    track[ip, y] = np.argmax(p[ip-1,:] + pyy[:,y])
    p[ip,y] = p[ip-1, track[ip, y]] + pyy[track[ip, y],y] + pyx[y,x]
    
count = len(input)-1 
s = ''
id = np.argmax(p[len(input) - 1, :])
while count > 0 :
  s = s + str(track[count, id])
  id = track[count, id]
  count = count - 1

print(p)
s = s[::-1]
print('track back :')
for i in range(len(s)):
  print(mapCharacter(int(s[i])))


[[ -4.32192809  -4.32192809  -5.32192809  -3.73696559]
 [ -8.05889369  -7.15842936  -8.38082178  -8.38082178]
 [-11.70274988 -11.80228555 -11.21732305 -13.80228555]
 [-16.27621674 -14.27621674 -14.86117924 -14.95428865]
 [-18.27621674 -18.92007293 -18.33511043 -20.92007293]
 [-24.97896662 -19.79078991 -22.39400412 -21.8496836 ]
 [-25.4346461  -23.4346461  -24.8496836  -23.8496836 ]
 [-27.5866492  -27.07850229 -26.49353979 -27.49353979]
 [-31.23050539 -29.55243348 -30.13739598 -30.23050539]]
track back :
Party
Tv
Pub
Study
Party
Tv
Tv
Pub
